version: '2'
services:
  database:
    build:
      context: ./MySQLDB
      dockerfile: Dockerfile-mysql-ja
    expose:
      - "3306"
    ports:
      - "3306:3306"
  activerecord-service:
    build:
      context: ./BackEnd
      dockerfile: Dockerfile-activerecord-service
    expose:
      - "4567"
    ports:
      - "4567:4567"
    depends_on: 
      - database